###Get a list of all products
GET http://localhost:3000/notes

### Create a product
POST http://localhost:3000/notes
Content-Type: application/json

{
  "noteName": "third note",
  "noteBody": "this is the third note"
}

### GET a product by id
GET http://localhost:3000/notes/643ae7783bc247547bf43b7a

### Update a product by id
PUT  http://localhost:3000/notes/643ae7783bc247547bf43b7a
Content-Type: application/json

{
  "noteBody": "actually this is the note"
}


### Delete a product by id
DELETE  http://localhost:3000/notes/643ae71e3bc247547bf43b73

### 404 route Not Found
GET http://localhost:3000/